// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvecuxqozqxbgjgyxqpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_pJNXe8B10TtJq0l9algrbg_zztriGJr";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);