// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pajirtvgatqrmntivycp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhamlydHZnYXRxcm1udGl2eWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzMTExOTAsImV4cCI6MjA5Mzg4NzE5MH0.q_7hxv7JoUHtU3gcQoaxVB-4IEQof7nvcaUm7lhA9tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);